### ISSUE TITLE
ARM64 7.16.1版本可以正常刷入ax2设备，但是安装无线驱动后winbox找不到机器了

### ISSUE THREAD

**Issue by xfshi** [FUjr/MikroTikPatch#5]
如题：ARM64 7.16.1版本可以正常刷入ax2设备，并且可以正常激活L6，但是安装无线驱动（NPK包）后winbox找不到机器了（只要安装[wireless-7.16.1-arm64.npk]包就会出现无法正常启动的情况），请问大佬是啥原因啊。

另外还有个问题，只要安装了routeros系统包以外的npk就无法恢复出厂设置。

**Comment by FUjr** [comment]
请安装wifi-qcom.
